jobs:
      - upload:
      - name: Upload build to hosting environment
        uses: Atyn/Simple-SFTP
        with:
          url: sftp://codydigi:PASSWORD@cody.digitalscholarship.brown.edu/www/1
          local-directory: 1
